-- ============================================================
-- 0011_ir_mf_rates
-- Insère 2 entrées dans annexe_table :
--   - ir_mf_rates  : IR + MF par escale (€), source CSV AF mai 2026
--   - zone_escales : 9 zones A81 → liste d'escales (référence visuelle)
-- ============================================================

insert into annexe_table (slug, name, description, data) values (
  'ir_mf_rates',
  'IR + MF — Tableau récapitulatif (€)',
  'Indemnités Repas + Menus Frais par escale, en euros (réf. avril 2026 du tableau AF "AU 1ER MAI 2026 V1"). Modifier ici pour ajouter les escales manquantes.',
  '[
    {"escale":"JNB","country":"AFRIQUE DU SUD","currency":"ZAR","ir_eur":22.28,"mf_eur":4.46},
    {"escale":"CPT","country":"AFRIQUE DU SUD","currency":"ZAR","ir_eur":22.28,"mf_eur":4.46},
    {"escale":"ALG","country":"ALGERIE","currency":"DZD","ir_eur":25.74,"mf_eur":5.15},
    {"escale":"ORN","country":"ALGERIE","currency":"DZD","ir_eur":25.74,"mf_eur":5.15},
    {"escale":"BER","country":"ALLEMAGNE","currency":"EUR","ir_eur":34.35,"mf_eur":6.87},
    {"escale":"NBJ","country":"ANGOLA","currency":"USD","ir_eur":24.70,"mf_eur":4.94},
    {"escale":"LAD","country":"ANGOLA","currency":"USD","ir_eur":24.70,"mf_eur":4.94},
    {"escale":"RUH","country":"ARABIE SAOUDITE","currency":"SAR","ir_eur":34.06,"mf_eur":6.81},
    {"escale":"EZE","country":"ARGENTINE","currency":"USD","ir_eur":37.47,"mf_eur":7.49},
    {"escale":"EVN","country":"ARMENIE","currency":"AMD","ir_eur":24.12,"mf_eur":4.82},
    {"escale":"VIE","country":"AUTRICHE","currency":"EUR","ir_eur":37.70,"mf_eur":7.54},
    {"escale":"COO","country":"BENIN","currency":"XOF","ir_eur":24.77,"mf_eur":4.95},
    {"escale":"GIG","country":"BRESIL","currency":"BRL","ir_eur":22.23,"mf_eur":4.45},
    {"escale":"GRU","country":"BRESIL","currency":"BRL","ir_eur":22.23,"mf_eur":4.45},
    {"escale":"FOR","country":"BRESIL","currency":"BRL","ir_eur":22.23,"mf_eur":4.45},
    {"escale":"DLA","country":"CAMEROUN","currency":"XAF","ir_eur":40.82,"mf_eur":8.16},
    {"escale":"YUL","country":"CANADA","currency":"CAD","ir_eur":34.56,"mf_eur":6.91},
    {"escale":"SCL","country":"CHILI","currency":"CLP","ir_eur":31.04,"mf_eur":6.21},
    {"escale":"PVG","country":"CHINE","currency":"CNY","ir_eur":26.21,"mf_eur":5.24},
    {"escale":"BOG","country":"COLOMBIE","currency":"COP","ir_eur":22.87,"mf_eur":4.57},
    {"escale":"BZV","country":"CONGO","currency":"XAF","ir_eur":42.69,"mf_eur":8.54},
    {"escale":"ICN","country":"COREE DU SUD","currency":"KRW","ir_eur":30.20,"mf_eur":6.04},
    {"escale":"SJO","country":"COSTA RICA","currency":"CRC","ir_eur":42.43,"mf_eur":8.49},
    {"escale":"ABJ","country":"COTE D IVOIRE","currency":"XOF","ir_eur":34.30,"mf_eur":6.86},
    {"escale":"DBV","country":"CROATIE","currency":"EUR","ir_eur":30.70,"mf_eur":6.14},
    {"escale":"HAV","country":"CUBA","currency":"USD","ir_eur":12.22,"mf_eur":2.44},
    {"escale":"CPH","country":"DANEMARK","currency":"DKK","ir_eur":56.06,"mf_eur":11.21},
    {"escale":"JIB","country":"DJIBOUTI","currency":"DJF","ir_eur":36.35,"mf_eur":7.27},
    {"escale":"CAI","country":"EGYPTE","currency":"EGP","ir_eur":18.84,"mf_eur":3.77},
    {"escale":"AUH","country":"EMIRATS ARABES UNIS","currency":"AED","ir_eur":35.93,"mf_eur":7.19},
    {"escale":"DXB","country":"EMIRATS ARABES UNIS","currency":"AED","ir_eur":35.93,"mf_eur":7.19},
    {"escale":"MAD","country":"ESPAGNE","currency":"EUR","ir_eur":32.75,"mf_eur":6.55},
    {"escale":"JFK","country":"ETATS UNIS","currency":"USD","ir_eur":44.71,"mf_eur":8.94},
    {"escale":"HEL","country":"FINLANDE","currency":"EUR","ir_eur":47.90,"mf_eur":9.58},
    {"escale":"FRA","country":"France","currency":"EUR","ir_eur":21.40,"mf_eur":4.28},
    {"escale":"LBV","country":"GABON","currency":"XAF","ir_eur":35.57,"mf_eur":7.11},
    {"escale":"TBS","country":"GEORGIE","currency":"GEL","ir_eur":19.64,"mf_eur":3.93},
    {"escale":"LHR","country":"GRANDE BRETAGNE","currency":"GBP","ir_eur":46.24,"mf_eur":9.25},
    {"escale":"ATH","country":"GRECE","currency":"EUR","ir_eur":34.95,"mf_eur":6.99},
    {"escale":"PTP","country":"GUADELOUPE","currency":"EUR","ir_eur":39.00,"mf_eur":7.80},
    {"escale":"CKY","country":"GUINEE","currency":"GNF","ir_eur":28.92,"mf_eur":5.78},
    {"escale":"SSG","country":"GUINEE EQUATORIALE","currency":"XAF","ir_eur":31.25,"mf_eur":6.25},
    {"escale":"CAY","country":"GUYANE FRANCAISE","currency":"EUR","ir_eur":41.00,"mf_eur":8.20},
    {"escale":"HKG","country":"HONG KONG","currency":"HKD","ir_eur":36.64,"mf_eur":7.33},
    {"escale":"BUD","country":"HONGRIE","currency":"HUF","ir_eur":31.92,"mf_eur":6.38},
    {"escale":"BLR","country":"INDE","currency":"INR","ir_eur":25.10,"mf_eur":5.02},
    {"escale":"BOM","country":"INDE","currency":"INR","ir_eur":25.10,"mf_eur":5.02},
    {"escale":"DEL","country":"INDE","currency":"INR","ir_eur":25.10,"mf_eur":5.02},
    {"escale":"MAA","country":"INDE","currency":"INR","ir_eur":25.10,"mf_eur":5.02},
    {"escale":"DUB","country":"IRLANDE","currency":"EUR","ir_eur":41.06,"mf_eur":8.21},
    {"escale":"TLV","country":"ISRAEL","currency":"ILS","ir_eur":51.88,"mf_eur":10.38},
    {"escale":"FCO","country":"ITALIE","currency":"EUR","ir_eur":34.30,"mf_eur":6.86},
    {"escale":"NRT","country":"JAPON","currency":"JPY","ir_eur":28.78,"mf_eur":5.76},
    {"escale":"NBO","country":"KENYA","currency":"KES","ir_eur":23.79,"mf_eur":4.76},
    {"escale":"RUN","country":"LA REUNION","currency":"EUR","ir_eur":33.00,"mf_eur":6.60},
    {"escale":"BEY","country":"LIBAN","currency":"USD","ir_eur":27.67,"mf_eur":5.53},
    {"escale":"TNR","country":"MADAGASCAR","currency":"MGA","ir_eur":26.12,"mf_eur":5.22},
    {"escale":"MLA","country":"MALTE","currency":"EUR","ir_eur":42.43,"mf_eur":8.49},
    {"escale":"RBA","country":"MAROC","currency":"MAD","ir_eur":27.41,"mf_eur":5.48},
    {"escale":"FDF","country":"MARTINIQUE","currency":"EUR","ir_eur":39.25,"mf_eur":7.85},
    {"escale":"MRU","country":"MAURICE","currency":"MUR","ir_eur":31.59,"mf_eur":6.32},
    {"escale":"NKC","country":"MAURITANIE","currency":"MRU","ir_eur":24.61,"mf_eur":4.92},
    {"escale":"CUN","country":"MEXIQUE","currency":"MXN","ir_eur":27.78,"mf_eur":5.56},
    {"escale":"MEX","country":"MEXIQUE","currency":"MXN","ir_eur":27.78,"mf_eur":5.56},
    {"escale":"ABV","country":"NIGERIA ABV","currency":"USD","ir_eur":21.89,"mf_eur":4.38},
    {"escale":"LOS","country":"NIGERIA LOS","currency":"USD","ir_eur":21.72,"mf_eur":4.34},
    {"escale":"PHC","country":"NIGERIA PHC","currency":"USD","ir_eur":15.46,"mf_eur":3.09},
    {"escale":"OSL","country":"NORVEGE","currency":"NOK","ir_eur":50.75,"mf_eur":10.15},
    {"escale":"PTY","country":"PANAMA","currency":"USD","ir_eur":32.36,"mf_eur":6.47},
    {"escale":"AMS","country":"PAYS-BAS","currency":"EUR","ir_eur":41.05,"mf_eur":8.21},
    {"escale":"LIM","country":"PEROU","currency":"PEN","ir_eur":32.53,"mf_eur":6.51},
    {"escale":"MNL","country":"PHILIPPINES","currency":"PHP","ir_eur":26.45,"mf_eur":5.29},
    {"escale":"WAW","country":"POLOGNE","currency":"PLN","ir_eur":31.86,"mf_eur":6.37},
    {"escale":"PPT","country":"POLYNESIE TAHITI","currency":"XPF","ir_eur":52.73,"mf_eur":10.55},
    {"escale":"LIS","country":"PORTUGAL","currency":"EUR","ir_eur":30.00,"mf_eur":6.00},
    {"escale":"PRG","country":"REPUBLIQUE TCHEQUE","currency":"CZK","ir_eur":29.88,"mf_eur":5.98},
    {"escale":"OTP","country":"ROUMANIE","currency":"RON","ir_eur":27.35,"mf_eur":5.47},
    {"escale":"SXM","country":"SAINT-MARTIN","currency":"EUR","ir_eur":40.00,"mf_eur":8.00},
    {"escale":"DSS","country":"SENEGAL","currency":"XOF","ir_eur":38.11,"mf_eur":7.62},
    {"escale":"BEG","country":"SERBIE","currency":"RSD","ir_eur":24.65,"mf_eur":4.93},
    {"escale":"SIN","country":"SINGAPOUR","currency":"SGD","ir_eur":33.44,"mf_eur":6.69},
    {"escale":"ARN","country":"SUEDE","currency":"SEK","ir_eur":45.06,"mf_eur":9.01},
    {"escale":"ZRH","country":"SUISSE","currency":"CHF","ir_eur":64.35,"mf_eur":12.87},
    {"escale":"ZNZ","country":"TANZANIE","currency":"USD","ir_eur":14.90,"mf_eur":2.98},
    {"escale":"NDJ","country":"TCHAD","currency":"XAF","ir_eur":45.54,"mf_eur":9.11},
    {"escale":"BKK","country":"THAILANDE","currency":"THB","ir_eur":31.00,"mf_eur":6.20},
    {"escale":"LFW","country":"TOGO","currency":"XOF","ir_eur":26.23,"mf_eur":5.25},
    {"escale":"TUN","country":"TUNISIE","currency":"TND","ir_eur":16.18,"mf_eur":3.24},
    {"escale":"IST","country":"TURQUIE","currency":"TRY","ir_eur":22.21,"mf_eur":4.44},
    {"escale":"SGN","country":"VIETNAM","currency":"USD","ir_eur":24.70,"mf_eur":4.94}
  ]'::jsonb
)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  data = excluded.data,
  updated_at = now();


insert into annexe_table (slug, name, description, data) values (
  'zone_escales',
  'Zones A81 → escales',
  'Référence visuelle : pour chaque zone Article 81, liste des escales connues. À mettre à jour quand une nouvelle escale apparaît, pour pouvoir l''ajouter avec le bon taux dans ir_mf_rates.',
  '[
    {"zone":"AME","escales":"ATL, BOS, DFW, DTW, EWR, IAD, IAH, JFK, LAS, LAX, MCO, MIA, ORD, PHX, RDU, SEA, SFO, YUL, YVR, YYZ"},
    {"zone":"CSA","escales":"BOG, EZE, FOR, GIG, GRU, HAV, LIM, PTY, SCL, SJO, SSA, CUN, MEX, PUJ"},
    {"zone":"AFR","escales":"ABJ, ABV, ALG, BZV, CAI, CKY, COO, CPT, DLA, DSS, FIH, JIB, JNB, JRO, LAD, LBV, LFW, LOS, NBJ, NBO, NDJ, NKC, NSI, ORN, PHC, PNR, RBA, SSG, TNR, ZNZ"},
    {"zone":"MGI","escales":"AUH, BEY, BLR, BOM, DEL, DXB, EVN, MAA, RUH, TBS, TLV"},
    {"zone":"APC","escales":"BKK, HKG, HND, ICN, KIX, MNL, NRT, PEK, PVG, SGN, SIN"},
    {"zone":"PAC","escales":"PPT"},
    {"zone":"COI","escales":"FDF, MRU, PTP, RUN, SXM, CAY"},
    {"zone":"EUR","escales":"AMS, ARN, ATH, BEG, BER, BUD, CPH, DBV, DUB, FCO, HEL, IST, LHR, LIS, MAD, MLA, OSL, OTP, PRG, VIE, WAW, ZRH"},
    {"zone":"FRA","escales":"CDG, ORY, NCE, MRS, LYS, TLS, BOD"}
  ]'::jsonb
)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  data = excluded.data,
  updated_at = now();
